# -*- coding: utf-8 -*-
"""irisdatasetEDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-ALv2OOJQDaDgAWaGIACUqpMitLwQCQA
"""

import pandas as pd
import numpy as np

from google.colab import files
uploaded=files.upload()

df = pd.read_csv("Iris.csv")

df

df.head()

df.tail()

df.info()

